### ISSUE TITLE
Can't install it with Packer

### ISSUE THREAD

**Issue by cloudUser98** [mweisshaupt1988/neobeans.vim#2]
I followed the instructions for the installation with Packer but it won't let me install the plugin.

The error is: ✗ Failed to install neobeans/neobeans.nvim

**Comment by mweisshaupt1988** [comment]
That's what I get for using full paths with vim-plug :D
I have fixed the install snippet in the readme. Please try again.

**Comment by cloudUser98** [comment]
@mweisshaupt1988 still the same :c
